### ISSUE TITLE
`LocationIO.writeUnsafe` must not use `putStream`

### ISSUE THREAD

**Issue by etorreborre** [ambiata/notion#53]
But `putFile` instead, see #52.

**Comment by charleso** [comment]
Can we remove `putStream`? It seems like a function that should never be called? There is `putStreamWithReadLimit` which would be the last resort if you can't do `putBytesWithMetadata`.

**Comment by markhibberd** [comment]
@charleso I don't see how.

`putStreamWithReadLimit` is not different or better than `putStream` in terms of limitations, in fact it is probably worse because if someone sets the read limit to something silly there is an extra chance of a bug.

Either of these is the only way to implement efficient streaming, and when you know the size ahead of time (e.g. hdfs -> s3 or a bunch of other situations where we have metadata or can predict size delta).

I wouldn't have a problem with renaming it to point out the risk though.

**Comment by charleso** [comment]
> I wouldn't have a problem with renaming it to point out the risk though.

Works for me.
